const agentConfig = [
  ['ceo','CEO AI','Direction & Decisions'], ['research','Research AI','Trends & Evidence'], ['idea','Idea AI','Ideas & Scoring'],
  ['writer','Writer AI','Scripts & Copy'], ['producer','Producer AI','Production Planning'], ['visual','Visual AI','Visual Assets'],
  ['video','Video AI','Video Assembly'], ['qa','QA AI','Quality & Risk'], ['publisher','Publisher AI','Publishing'], ['analytics','Analytics AI','Performance & Learning']
];
let companyState = null, agents = [], tasks = [], handoffs = [];
const statusText = {WORKING:'WORKING',WAITING_APPROVAL:'WAITING',READY:'READY',IDLE:'IDLE',BLOCKED:'BLOCKED',ERROR:'ERROR',OFFLINE:'OFFLINE'};
const roleColor = s => ['WAITING_APPROVAL','BLOCKED','ERROR'].includes(s) ? 'wait' : ['WORKING','ASSIGNED'].includes(s) ? 'busy' : '';

function normalizeState(state){
  const src=state?.agents||{};
  agents=agentConfig.map(([id,name,role])=>{const s=src[id]||{};const t=(state.tasks||[]).find(x=>x.task_id===s.current_task_id)||(state.tasks||[]).find(x=>x.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(x.status));return {id,name,role,status:s.status||'IDLE',task:t?.title||(s.last_error?`ERROR: ${s.last_error}`:'พร้อมรับงาน'),currentTaskId:s.current_task_id||null,bubble:s.status==='WAITING_APPROVAL'?'OWNER DECISION':s.status==='WORKING'?'WORKING':s.status||'IDLE'};});
  tasks=state.tasks||[]; handoffs=state.handoffs||[];
}
function agentMarkup(a){return `<div class="room ${a.id}" data-agent="${a.id}"><div class="room-label">${a.name.replace(' AI','')}</div><div class="room-sub">${a.role}</div><div class="status-dot ${roleColor(a.status)}"></div><div class="desk"></div><div class="monitor"></div><div class="chair"></div><div class="agent" data-agent="${a.id}"><div class="head"><div class="hair"></div></div><div class="body"></div><div class="leg l"></div><div class="leg r"></div><div class="bubble">${a.bubble}</div></div></div>`;}
function renderRooms(){document.querySelector('#rooms').innerHTML=agents.map(agentMarkup).join('')+`<div class="room lounge"><div class="room-label">LOUNGE</div><div class="room-sub">break / team sync</div></div>`;document.querySelectorAll('[data-agent]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openAgent(el.dataset.agent);}));}

async function apiGet(path){const r=await fetch(path,{cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
async function apiPost(path, body={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
async function refreshAfterAction(message){showToast(message);await loadCompanyState();}

function taskControls(task){
  if(!task)return '';
  if(task.status==='WAITING_APPROVAL'&&task.owner_agent_id==='ceo') return `<div class="action-row"><button class="mini-btn primary" id="approveTaskBtn">APPROVE CEO</button><button class="mini-btn danger" id="rejectTaskBtn">REJECT</button></div>`;
  if(task.status==='IN_PROGRESS'&&task.owner_agent_id==='qa') return `<div class="action-row"><button class="mini-btn danger" id="rejectQaBtn">REQUEST REVISION</button><button class="mini-btn primary" id="completeTaskBtn">PASS QA</button></div>`;
  if(['QUEUED','ASSIGNED'].includes(task.status)) return `<div class="action-row"><button class="mini-btn primary" id="runTaskBtn">RUN ${task.owner_agent_id.toUpperCase()}</button></div>`;
  if(task.status==='IN_PROGRESS') return `<div class="action-row"><button class="mini-btn primary" id="completeTaskBtn">COMPLETE TASK</button></div>`;
  return '';
}
function wireTaskControls(task){
  const run=document.querySelector('#runTaskBtn'),complete=document.querySelector('#completeTaskBtn'),approve=document.querySelector('#approveTaskBtn'),reject=document.querySelector('#rejectTaskBtn'),rejectQa=document.querySelector('#rejectQaBtn');
  if(run)run.onclick=async()=>{try{await apiPost(`/api/tasks/${task.task_id}/execute`,{input:{source:'pixel-office'}});await refreshAfterAction(`${task.owner_agent_id.toUpperCase()} is working`);openAgent(task.owner_agent_id);}catch(e){showToast(e.message);}};
  if(complete)complete.onclick=async()=>{try{const result=await apiPost(`/api/tasks/${task.task_id}/complete`,{});await refreshAfterAction(result.approval_required?'CEO approval required':result.nextTask?`Handoff → ${result.nextTask.owner_agent_id.toUpperCase()}`:'Task completed');openAgent(task.owner_agent_id);}catch(e){showToast(e.message);}};
  if(approve)approve.onclick=async()=>{try{await apiPost(`/api/tasks/${task.task_id}/approve`,{comment:'Approved from Pixel Office'});await refreshAfterAction('CEO approved — Writer task created');openAgent('ceo');}catch(e){showToast(e.message);}};
  if(reject)reject.onclick=async()=>{try{await apiPost(`/api/tasks/${task.task_id}/reject`,{reason:'Owner rejected recommendation from Pixel Office'});await refreshAfterAction('CEO recommendation rejected');openAgent('ceo');}catch(e){showToast(e.message);}};
  if(rejectQa)rejectQa.onclick=async()=>{try{await apiPost(`/api/tasks/${task.task_id}/reject`,{reason:'QA requested revision from Pixel Office'});await refreshAfterAction('Revision sent back to Writer');openAgent('qa');}catch(e){showToast(e.message);}};
}
function openAgent(id){const a=agents.find(x=>x.id===id);if(!a)return;const open=tasks.filter(t=>t.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(t.status));const task=open.find(t=>t.task_id===a.currentTaskId)||open[0]||null;const incoming=handoffs.filter(h=>h.to_agent===id&&['PENDING','ACCEPTED'].includes(h.status));const outgoing=handoffs.filter(h=>h.from_agent===id);const ev=id==='research'?(companyState.evidence||[]).length:0;const src=id==='research'?(companyState.sources||[]).length:0;document.querySelector('#sidePanel').classList.remove('hidden');document.querySelector('#panelContent').innerHTML=`<div class="employee"><h2>${a.name}</h2><div class="role">${a.role}</div><div class="status-line ${roleColor(a.status)}"><b>${statusText[a.status]||a.status}</b><br><span>${a.task}</span></div><div class="metric-grid"><div class="metric"><b>${open.length}</b><span>Open Tasks</span></div><div class="metric"><b>${task?.priority||'—'}</b><span>Priority</span></div><div class="metric"><b>${ev||'—'}</b><span>Evidence</span></div><div class="metric"><b>${src||'—'}</b><span>Sources</span></div></div><div class="task-box"><strong>Current Task</strong><p>${task?`${task.title} · ${task.status}`:'ไม่มีงานที่กำลังเปิดอยู่'}</p>${taskControls(task)}</div><div class="task-box"><strong>Handoff</strong><p>${incoming.length?`รับงานจาก ${incoming.map(h=>h.from_agent).join(', ')}`:outgoing.length?`ส่งงานแล้ว ${outgoing.length} รายการ`:'ยังไม่มี handoff'}</p></div><div class="task-box"><strong>Role Runtime</strong><p>คำสั่งงานของ agent ถูกจำกัดตาม role และผลลัพธ์ถูกบันทึกใน Company Core</p></div></div>`;wireTaskControls(task);}
function openAiCore(){document.querySelector('#sidePanel').classList.remove('hidden');document.querySelector('#panelContent').innerHTML=`<div class="employee"><h2>AI CORE</h2><div class="role">LLM Runtime Configuration</div><div id="llmStatusBox" class="task-box"><strong>กำลังตรวจสอบ...</strong><p>อ่านเฉพาะสถานะจาก environment — ไม่มี API key แสดงบนหน้าเว็บ</p></div><div class="task-box"><strong>Configuration</strong><p>ตั้งค่า <code>AI_BASE_URL</code>, <code>AI_MODEL</code> และ <code>AI_API_KEY</code> ที่ runtime environment เท่านั้น ไม่เก็บ secret ใน repository</p></div><div class="task-box"><strong>Execution Policy</strong><p>LLM ถูกเรียกตาม role ของ Agent แต่ละตัว และระบบยังคงเก็บ structured output / evidence taxonomy ใน Company Core</p></div></div>`;loadLlmStatus();}
async function loadLlmStatus(){const box=document.querySelector('#llmStatusBox');if(!box)return;try{const s=await apiGet('/api/llm-status');box.innerHTML=`<strong>${s.configured?'● LLM READY':'○ LLM NOT CONFIGURED'}</strong><p>Provider: ${s.provider}</p><p>Model: ${s.model||'ยังไม่ได้ตั้งค่า'}</p><p>Base URL: ${s.base_url}</p><p>API key: ${s.api_key_configured?'configured':'not configured'}</p><p>Credentials: ${s.credentials_source}</p>`;}catch(e){box.innerHTML=`<strong>LLM STATUS ERROR</strong><p>${e.message}</p>`;}}
function renderTaskBadge(){document.querySelector('#taskBadge').textContent=tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length;const p=(companyState?.approvals||[]).filter(a=>a.status==='PENDING').length;document.querySelector('#approvalBtn').innerHTML=`⚠ APPROVAL <b>${p}</b>`;}
function renderPipeline(){const el=document.querySelector('#pipeline');if(!el)return;const order=['research','idea','ceo','writer','producer','visual','video','qa','publisher','analytics'];el.innerHTML=order.map(id=>{const a=agents.find(x=>x.id===id),t=tasks.find(x=>x.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(x.status));return `<div class="pipeline-node ${roleColor(a?.status||'')}"><b>${a?.name||id}</b><span>${t?.status||a?.status||'IDLE'}</span></div>`}).join('<div class="pipeline-arrow">→</div>');}
function showToast(message){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=message;document.querySelector('.office-wrap').appendChild(t);setTimeout(()=>t.remove(),2600);}
async function loadCompanyState(){try{companyState=await apiGet('/api/company-state');normalizeState(companyState);renderRooms();renderTaskBadge();renderPipeline();document.querySelector('.live-dot').title='Company Core connected';}catch(e){showToast('Company Core connection failed');console.error(e);}}
document.querySelector('#closePanel').onclick=()=>document.querySelector('#sidePanel').classList.add('hidden');document.querySelector('#tasksBtn').onclick=()=>{renderPipeline();showToast(`${tasks.length} tasks in Company Core`);};document.querySelector('#approvalBtn').onclick=()=>openAgent('ceo');document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(btn.dataset.view==='llm')openAiCore();else showToast(`${btn.dataset.view.toUpperCase()} view — live Company Core data`);});setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString('th-TH'),1000);setInterval(loadCompanyState,10000);loadCompanyState();