const agentConfig = [
  ['ceo','CEO AI','Direction & Decisions'], ['research','Research AI','Trends & Evidence'], ['idea','Idea AI','Ideas & Scoring'],
  ['writer','Writer AI','Scripts & Copy'], ['producer','Producer AI','Production Planning'], ['visual','Visual AI','Visual Assets'],
  ['video','Video AI','Video Assembly'], ['qa','QA AI','Quality & Risk'], ['publisher','Publisher AI','Publishing'], ['analytics','Analytics AI','Performance & Learning']
];
let companyState = null, agents = [], tasks = [], handoffs = [];
const statusText = {WORKING:'WORKING',WAITING_APPROVAL:'WAITING',READY:'READY',IDLE:'IDLE',BLOCKED:'BLOCKED',ERROR:'ERROR',OFFLINE:'OFFLINE'};
const roleColor = s => ['WAITING_APPROVAL','BLOCKED','ERROR'].includes(s) ? 'wait' : ['WORKING','ASSIGNED'].includes(s) ? 'busy' : '';

function normalizeState(state){
  const src=state?.agents||{};
  agents=agentConfig.map(([id,name,role])=>{const s=src[id]||{};const t=(state.tasks||[]).find(x=>x.task_id===s.current_task_id)||(state.tasks||[]).find(x=>x.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(x.status));return {id,name,role,status:s.status||'IDLE',task:t?.title||(s.last_error?`ERROR: ${s.last_error}`:'พร้อมรับงาน'),currentTaskId:s.current_task_id||null,bubble:s.status==='WAITING_APPROVAL'?'OWNER DECISION':s.status==='WORKING'?'WORKING':s.status||'IDLE'};});
  tasks=state.tasks||[]; handoffs=state.handoffs||[];
}
function agentMarkup(a){return `<div class="room ${a.id}" data-agent="${a.id}"><div class="room-label">${a.name.replace(' AI','')}</div><div class="room-sub">${a.role}</div><div class="status-dot ${roleColor(a.status)}"></div><div class="desk"></div><div class="monitor"></div><div class="chair"></div><div class="agent" data-agent="${a.id}"><div class="head"><div class="hair"></div></div><div class="body"></div><div class="leg l"></div><div class="leg r"></div><div class="bubble">${a.bubble}</div></div></div>`;}
function renderRooms(){document.querySelector('#rooms').innerHTML=agents.map(agentMarkup).join('')+`<div class="room lounge"><div class="room-label">LOUNGE</div><div class="room-sub">break / team sync</div></div>`;document.querySelectorAll('[data-agent]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openAgent(el.dataset.agent);}));}
function openAgent(id){const a=agents.find(x=>x.id===id);if(!a)return;const open=tasks.filter(t=>t.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(t.status));const incoming=handoffs.filter(h=>h.to_agent===id&&['PENDING','ACCEPTED'].includes(h.status));const outgoing=handoffs.filter(h=>h.from_agent===id);const ev=id==='research'?(companyState.evidence||[]).length:0;const src=id==='research'?(companyState.sources||[]).length:0;document.querySelector('#sidePanel').classList.remove('hidden');document.querySelector('#panelContent').innerHTML=`<div class="employee"><h2>${a.name}</h2><div class="role">${a.role}</div><div class="status-line ${roleColor(a.status)}"><b>${statusText[a.status]||a.status}</b><br><span>${a.task}</span></div><div class="metric-grid"><div class="metric"><b>${open.length}</b><span>Open Tasks</span></div><div class="metric"><b>${open[0]?.priority||'—'}</b><span>Priority</span></div><div class="metric"><b>${ev||'—'}</b><span>Evidence</span></div><div class="metric"><b>${src||'—'}</b><span>Sources</span></div></div><div class="task-box"><strong>Current Task</strong><p>${open[0]?`${open[0].title} · ${open[0].status}`:'ไม่มีงานที่กำลังเปิดอยู่'}</p></div><div class="task-box"><strong>Handoff</strong><p>${incoming.length?`รับงานจาก ${incoming.map(h=>h.from_agent).join(', ')}`:outgoing.length?`ส่งงานแล้ว ${outgoing.length} รายการ`:'ยังไม่มี handoff'}</p></div><div class="task-box"><strong>Ask this AI</strong><p>Agent runtime จะตอบตาม role และข้อมูลของ agent นี้</p><button class="mini-btn" onclick="showToast('Agent runtime ยังไม่เปิดใช้งาน')">ASK ${a.name.toUpperCase()}</button></div></div>`;}
function renderTaskBadge(){document.querySelector('#taskBadge').textContent=tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length;const p=(companyState?.approvals||[]).filter(a=>a.status==='PENDING').length;document.querySelector('#approvalBtn').innerHTML=`⚠ APPROVAL <b>${p}</b>`;}
function renderPipeline(){const el=document.querySelector('#pipeline');if(!el)return;const order=['research','idea','ceo','writer','producer','visual','video','qa','publisher','analytics'];el.innerHTML=order.map(id=>{const a=agents.find(x=>x.id===id),t=tasks.find(x=>x.owner_agent_id===id&&!['COMPLETED','CANCELLED'].includes(x.status));return `<div class="pipeline-node ${roleColor(a?.status||'')}"><b>${a?.name||id}</b><span>${t?.status||a?.status||'IDLE'}</span></div>`}).join('<div class="pipeline-arrow">→</div>');}
function showToast(message){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=message;document.querySelector('.office-wrap').appendChild(t);setTimeout(()=>t.remove(),2600);}
async function loadCompanyState(){try{const r=await fetch('/api/company-state',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);companyState=await r.json();normalizeState(companyState);renderRooms();renderTaskBadge();renderPipeline();document.querySelector('.live-dot').title='Company Core connected';}catch(e){showToast('Company Core connection failed');console.error(e);}}
document.querySelector('#closePanel').onclick=()=>document.querySelector('#sidePanel').classList.add('hidden');document.querySelector('#tasksBtn').onclick=()=>{renderPipeline();showToast(`${tasks.length} tasks in Company Core`);};document.querySelector('#approvalBtn').onclick=()=>openAgent('ceo');document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');showToast(`${btn.dataset.view.toUpperCase()} view — live Company Core data`);});setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString('th-TH'),1000);setInterval(loadCompanyState,10000);loadCompanyState();